server:
  port: 7272

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/secondhand?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      password: 123456
      host: localhost
  ai:
    deepseek:
      api-key: sk-50add0881c8441c382ab9b82a7d7dc26 # 建议放环境变量，演示写死
      base-url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      chat:
        options:
          model: deepseek-chat                      # 必须填这个模型名
          temperature: 0.7
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.seateam.secondhand_system.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET:secondhand_system_jwt_secret_key_2025}
  expiration: 86400000
